--PLU-Infection Cure
function c20100010.initial_effect(c)
	c:SetUniqueOnField(1,0,20100010)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetHintTiming(0,TIMING_END_PHASE)
	c:RegisterEffect(e1)
	--LP recover
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e2:SetCode(EVENT_SUMMON_SUCCESS)
	e2:SetProperty(EFFECT_FLAG_DELAY)
	e2:SetRange(LOCATION_SZONE)
	e2:SetLabel(1)
	e2:SetCondition(c20100010.lpcon)
	e2:SetOperation(c20100010.lpop1)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_CONTINUOUS+EFFECT_TYPE_FIELD)
	e3:SetProperty(EFFECT_FLAG_DELAY)
	e3:SetCode(EVENT_SPSUMMON_SUCCESS)
	e3:SetRange(LOCATION_SZONE)
	e3:SetLabel(1)
	e3:SetCondition(c20100010.lpcon1)
	e3:SetOperation(c20100010.lpop1)
	c:RegisterEffect(e3)
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_CONTINUOUS+EFFECT_TYPE_FIELD)
	e4:SetCode(EVENT_SPSUMMON_SUCCESS)
	e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e4:SetRange(LOCATION_SZONE)
	e4:SetLabel(1)
	e4:SetCondition(c20100010.regcon)
	e4:SetOperation(c20100010.regop)
	c:RegisterEffect(e4)
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_CONTINUOUS+EFFECT_TYPE_FIELD)
	e5:SetCode(EVENT_CHAIN_SOLVED)
	e5:SetRange(LOCATION_SZONE)
	e5:SetCondition(c20100010.lpcon2)
	e5:SetOperation(c20100010.lpop2)
	e5:SetLabelObject(e4)
	c:RegisterEffect(e5)
	--disable summon
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_FIELD)
	e6:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e6:SetRange(LOCATION_SZONE)
	e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e6:SetTargetRange(1,0)
	e6:SetTarget(c20100010.sumlimit)
	c:RegisterEffect(e6)
	local e7=e6:Clone()
	e7:SetCode(EFFECT_CANNOT_SUMMON)
	c:RegisterEffect(e7)
	local e8=e6:Clone()
	e8:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
	c:RegisterEffect(e8)
	--setcard
	local e9=Effect.CreateEffect(c)
	e9:SetType(EFFECT_TYPE_FIELD)
	e9:SetRange(LOCATION_SZONE)
	e9:SetTargetRange(LOCATION_ONFIELD,LOCATION_ONFIELD)
	e9:SetCode(EFFECT_ADD_SETCODE)
	e9:SetValue(0xb28)
	e9:SetTarget(aux.TargetBoolFunction(Card.IsFaceup))
	c:RegisterEffect(e9)
end
function c20100010.sumlimit(e,c,sump,sumtype,sumpos,targetp)
	return not c:IsSetCard(0xb28)
end
function c20100010.cfilter(c,sp)
	return c:IsSummonPlayer(sp) and c:IsSetCard(0xb28) and c:IsFaceup()
end
function c20100010.lpcon(e,tp,eg,ep,ev,re,r,rp)
	return eg:IsExists(c20100010.cfilter,1,nil,1-tp)
end
function c20100010.lpcon1(e,tp,eg,ep,ev,re,r,rp)
	return c20100010.lpcon(e,tp,eg,ep,ev,re,r,rp)
		and not Duel.IsChainSolving()
end
function c20100010.lpop1(e,tp,eg,ep,ev,re,r,rp)
	local lg=eg:Filter(c20100010.cfilter,nil,1-tp)
	local rnum=lg:GetSum(Card.GetAttack)
	Duel.Recover(tp,rnum,REASON_EFFECT)
end
function c20100010.regcon(e,tp,eg,ep,ev,re,r,rp)
	return c20100010.lpcon(e,tp,eg,ep,ev,re,r,rp)
		and Duel.IsChainSolving()
end
function c20100010.regop(e,tp,eg,ep,ev,re,r,rp)
	local lg=eg:Filter(c20100010.cfilter,nil,1-tp)
	local g=e:GetLabelObject()
	if g==nil or #g==0 then
		lg:KeepAlive()
		e:SetLabelObject(lg)
	else
		g:Merge(lg)
	end
	e:GetHandler():RegisterFlagEffect(20100010,RESET_EVENT+RESETS_STANDARD+RESET_CHAIN,0,1)
end
function c20100010.lpcon2(e,tp,eg,ep,ev,re,r,rp)
	return e:GetHandler():GetFlagEffect(20100010)>0
end
function c20100010.lpop2(e,tp,eg,ep,ev,re,r,rp)
	e:GetHandler():ResetFlagEffect(20100010)
	local lg=e:GetLabelObject():GetLabelObject()
	local rnum=lg:GetSum(Card.GetAttack)
	local g=Group.CreateGroup()
	g:KeepAlive()
	e:GetLabelObject():SetLabelObject(g)
	lg:DeleteGroup()
	Duel.Recover(tp,rnum,REASON_EFFECT)
end