--奥伯龙·伏提庚
local cm,m,o=GetID()
function cm.initial_effect(c)
    c:EnableReviveLimit()
    --special summon
    local e1=Effect.CreateEffect(c)
    e1:SetCategory(CATEGORY_REMOVE+CATEGORY_SPECIAL_SUMMON)
    e1:SetType(EFFECT_TYPE_IGNITION)
    e1:SetRange(LOCATION_HAND)
    e1:SetCountLimit(1,m)
    e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
    e1:SetTarget(cm.sptg)
    e1:SetOperation(cm.spop)
    c:RegisterEffect(e1)
    local e2=Effect.CreateEffect(c)
    e2:SetCategory(CATEGORY_DISABLE)
    e2:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F)
    e2:SetCode(EVENT_SPSUMMON_SUCCESS)
    e2:SetCountLimit(1,m+1)
    e2:SetTarget(cm.tg)
    e2:SetOperation(cm.op)
    c:RegisterEffect(e2)
    local e3=Effect.CreateEffect(c)
    e3:SetCategory(CATEGORY_ATKCHANGE)
    e3:SetType(EFFECT_TYPE_IGNITION)
    e3:SetRange(LOCATION_MZONE)
    e3:SetCountLimit(1,m+2)
    e3:SetCost(cm.cost1)
    e3:SetTarget(cm.tg1)
    e3:SetOperation(cm.op1)
    c:RegisterEffect(e3)
end
function cm.cfilter1(c)
    return c:IsType(TYPE_RITUAL) and c:IsAbleToRemove()
end
function cm.cfilter2(c)
    return c:IsType(TYPE_FUSION) and c:IsAbleToRemove()
end
function cm.cfilter3(c)
    return c:IsType(TYPE_SYNCHRO) and c:IsAbleToRemove()
end
function cm.cfilter4(c)
    return c:IsType(TYPE_LINK) and c:IsAbleToRemove()
end
function cm.sptg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
    if chkc then return false end
    local c=e:GetHandler()
    local a=Duel.IsExistingTarget(cm.cfilter1,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,nil)
        and Duel.IsExistingTarget(cm.cfilter2,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,nil)
        and Duel.IsExistingTarget(cm.cfilter3,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,nil)
        and Duel.IsExistingTarget(cm.cfilter4,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,nil)
    if chk==0 then return a
        and Duel.GetLocationCount(tp,LOCATION_MZONE)>0 and c:IsCanBeSpecialSummoned(e,0,tp,true,true) end
    Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_REMOVE)
    local g1=Duel.SelectTarget(tp,cm.cfilter1,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,1,nil):GetFirst()
    local g2=Duel.SelectTarget(tp,cm.cfilter2,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,1,nil):GetFirst()
    local g3=Duel.SelectTarget(tp,cm.cfilter3,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,1,nil):GetFirst()
    local g4=Duel.SelectTarget(tp,cm.cfilter4,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,1,nil):GetFirst()
    local g=Group.FromCards(g1,g2,g3,g4)
    Duel.SetOperationInfo(0,CATEGORY_REMOVE,g,4,0,0)
    Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,c,1,0,0)
end
function cm.spop(e,tp,eg,ep,ev,re,r,rp)
    local c=e:GetHandler()
    local g=Duel.GetChainInfo(0,CHAININFO_TARGET_CARDS):Filter(Card.IsRelateToEffect,nil,e)
    if c:IsRelateToEffect(e) and Duel.SpecialSummon(c,0,tp,tp,true,true,POS_FACEUP)>0 then
        c:CompleteProcedure()
        Duel.Remove(g,POS_FACEUP,REASON_EFFECT)
    end
    local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_FIELD)
    e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
    e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
    e1:SetReset(RESET_PHASE+PHASE_END)
    e1:SetTargetRange(1,0)
    Duel.RegisterEffect(e1,tp)
end
function cm.tg(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return true end
    local g=Duel.GetMatchingGroup(aux.NegateMonsterFilter,tp,0,LOCATION_MZONE,nil)
    Duel.SetOperationInfo(0,CATEGORY_DISABLE,g,g:GetCount(),0,0)
end
function cm.op(e,tp,eg,ep,ev,re,r,rp)
    local g=Duel.GetMatchingGroup(aux.NegateMonsterFilter,tp,0,LOCATION_MZONE,nil)
    local tc=g:GetFirst()
    while tc do
        local e1=Effect.CreateEffect(e:GetHandler())
        e1:SetType(EFFECT_TYPE_SINGLE)
        e1:SetCode(EFFECT_DISABLE)
        e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
        tc:RegisterEffect(e1)
        local e2=Effect.CreateEffect(e:GetHandler())
        e2:SetType(EFFECT_TYPE_SINGLE)
        e2:SetCode(EFFECT_DISABLE_EFFECT)
        e2:SetValue(RESET_TURN_SET)
        e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
        tc:RegisterEffect(e2)
        tc=g:GetNext()
    end
    if e:IsHasType(EFFECT_TYPE_ACTIVATE) then
        local e2=Effect.CreateEffect(e:GetHandler())
        e2:SetType(EFFECT_TYPE_FIELD)
        e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
        e2:SetCode(EFFECT_CHANGE_DAMAGE)
        e2:SetTargetRange(0,1)
        e2:SetValue(0)
        e2:SetReset(RESET_PHASE+PHASE_END)
        Duel.RegisterEffect(e2,tp)
        local e4=e2:Clone()
        e4:SetCode(EFFECT_NO_EFFECT_DAMAGE)
        e4:SetReset(RESET_PHASE+PHASE_END)
        Duel.RegisterEffect(e4,tp)
    end
end
function cm.cost1(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return true end
    Duel.PayLPCost(tp,math.floor(Duel.GetLP(tp)/2))
end
function cm.tg1(e,tp,eg,ep,ev,re,r,rp,chk)
    local g=Duel.GetMatchingGroup(Card.IsFaceup,tp,LOCATION_MZONE,LOCATION_MZONE,nil)
    if chk==0 then return g:GetCount()>0 end
    Duel.SetOperationInfo(0,CATEGORY_ATKCHANGE,g,1,0,0)
end
function cm.op1(e,tp,eg,ep,ev,re,r,rp)
    local g=Duel.GetMatchingGroup(Card.IsFaceup,tp,LOCATION_MZONE,LOCATION_MZONE,nil)
    if g:GetCount()>0 then
        Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(97453744,2))
        local sg=g:Select(tp,1,1,nil)
        Duel.HintSelection(sg)
        local tc=sg:GetFirst()
        local e1=Effect.CreateEffect(e:GetHandler())
        e1:SetType(EFFECT_TYPE_SINGLE)
        e1:SetCode(EFFECT_SET_ATTACK_FINAL)
        e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
        e1:SetValue(tc:GetAttack()*2)
        e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END)
        tc:RegisterEffect(e1)
        local e2=Effect.CreateEffect(e:GetHandler())
        e2:SetType(EFFECT_TYPE_SINGLE)
        e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_OATH)
        e2:SetCode(EFFECT_CANNOT_DIRECT_ATTACK)
        e2:SetReset(RESET_EVENT+RESETS_STANDARD)
        tc:RegisterEffect(e2)
        local e4=Effect.CreateEffect(e:GetHandler())
        e4:SetType(EFFECT_TYPE_SINGLE)
        e4:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
        e4:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
        e4:SetRange(LOCATION_MZONE)
        e4:SetReset(RESET_EVENT+RESETS_STANDARD)
        e4:SetValue(1)
        tc:RegisterEffect(e4)
        local e5=e4:Clone()
        e5:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
        e5:SetValue(cm.fuslimit)
        tc:RegisterEffect(e5)
        local e6=e4:Clone()
        e6:SetCode(EFFECT_CANNOT_BE_XYZ_MATERIAL)
        tc:RegisterEffect(e6)
        local e7=e4:Clone()
        e7:SetCode(EFFECT_CANNOT_BE_LINK_MATERIAL)
        tc:RegisterEffect(e7)
        local fid=e:GetHandler():GetFieldID()
        tc:RegisterFlagEffect(m,RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END,0,1,fid)
        local e3=Effect.CreateEffect(e:GetHandler())
        e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
        e3:SetCode(EVENT_PHASE+PHASE_END)
        e3:SetReset(RESET_PHASE+PHASE_END)
        e3:SetCountLimit(1)
        e3:SetLabel(fid)
        e3:SetLabelObject(tc)
        e3:SetCondition(cm.con2)
        e3:SetOperation(cm.op2)
        Duel.RegisterEffect(e3,tp)
    end
end
function cm.fuslimit(e,c,sumtype)
    return sumtype==SUMMON_TYPE_FUSION
end
function cm.con2(e,tp,eg,ep,ev,re,r,rp)
    local tc=e:GetLabelObject()
    if tc:GetFlagEffectLabel(m)~=e:GetLabel() then
        e:Reset()
        return false
    else return true end
end
function cm.op2(e,tp,eg,ep,ev,re,r,rp)
    local tc=e:GetLabelObject()
    local e3=Effect.CreateEffect(e:GetHandler())
    e3:SetType(EFFECT_TYPE_SINGLE)
    e3:SetCode(EFFECT_SET_ATTACK_FINAL)
    e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
    e3:SetValue(0)
    e3:SetReset(RESET_EVENT+RESETS_STANDARD)
    tc:RegisterEffect(e3)
    if tc:IsCanBeDisabledByEffect(e) then
        Duel.NegateRelatedChain(tc,RESET_TURN_SET)
        local e1=Effect.CreateEffect(e:GetHandler())
        e1:SetType(EFFECT_TYPE_SINGLE)
        e1:SetCode(EFFECT_DISABLE)
        e1:SetReset(RESET_EVENT+RESETS_STANDARD)
        tc:RegisterEffect(e1)
        local e2=Effect.CreateEffect(e:GetHandler())
        e2:SetType(EFFECT_TYPE_SINGLE)
        e2:SetCode(EFFECT_DISABLE_EFFECT)
        e2:SetValue(RESET_TURN_SET)
        e2:SetReset(RESET_EVENT+RESETS_STANDARD)
        tc:RegisterEffect(e2)
    end
end